services:
  nats:
    image: nats:2.9.15-alpine
    command: -js -DV -m 8222
    ports:
      - ${NATS_SERVER_PORT}:4222
    healthcheck:
       # printf 'GET /healthz?js-enabled=true HTTP/1.1\r\nHost: localhost:8222\r\n\r\n' | nc -w 1 localhost 8222 | tail -n 1 | grep -q '{"status":"ok"}'
        test: ["CMD-SHELL", "printf 'GET /healthz?js-enabled-only=true HTTP/1.1\r\nHost: localhost:8222\r\n\r\n' | nc -w 1 localhost 8222 | tail -n 1 | grep -q '{\"status\":\"ok\"}'"]
        interval: 1s
        timeout: 5s
        retries: 5

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
#    volumes:
#      - postgres-db-test:/var/lib/postgresql/data
    healthcheck:
      #      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      test: ['CMD-SHELL', "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1'"]
      interval: 1s
      timeout: 5s
      retries: 5
  waiting-for-the-services-to-be-ready:
    image: hello-world
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_healthy
#volumes:
#  postgres-db-test:
