#!/usr/bin/env bash

set -eou pipefail

dir=$(dirname "$0")
source "$dir"/exports

echo -e "\e[1;32mCreating services:\e[0m"
docker compose -f "$dir"/docker-compose.test.yml up -d
bash "$dir"/test --build