#!/usr/bin/env bash

set -eou pipefail

num_args=$#
if [[ $num_args -ne 1 ]]; then
  >&2 echo -e "\e[1;31mInvalid number of arguments. Only one arg\e[0m"
  exit 1
fi
cmd=$1
>&2 echo "command: $cmd"

export COMPOSE_PROJECT_NAME=tickets-api-test
dir=$(dirname "$0")
export POSTGRES_PORT=${POSTGRES_PORT:-5569}
export POSTGRES_USER=${POSTGRES_USER:-jorge}
export POSTGRES_DB=${POSTGRES_DB:-tickets}
export POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-123456}
docker compose -f "$dir"/docker-compose.test.yml exec -it db psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -t -c "$cmd"
