name: build_image
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  code_quality_check:
    uses: ./.github/workflows/code-quality-check.yml
    secrets: inherit
  docker:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    needs: [code_quality_check]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jym272/ticketing-tickets-api:latest
          cache-from: type=registry,ref=jym272/ticketing-tickets-api:latest
          cache-to: type=inline
      -
        name: Update repo readme description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: jym272/ticketing-tickets-api