name: comment_on_pr

on:
  workflow_run:
    types:
      - completed
    workflows:
      - pull_request
jobs:
  delete-comment:
    timeout-minutes: 2
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      -
        name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: 'github-actions[bot]'
          body-includes: tests_result_table
      -
        name: Delete Comment
        if: steps.find-comment.outputs.comment-id != ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ steps.find-comment.outputs.comment-id }}
  comment:
    timeout-minutes: 2
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      -
        name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pull_request.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: test-report
      -
        name: Analyze report
        id: analyze-report
        run: |
          # Extract the status field and count the number of times each value occurs
          status_counts=$(jq '.suites[].suites[].specs[].tests[].status' test-results.json | sort | uniq -c)
          
          # Extract the count of the "expected" status value
          count_expected=$(echo "$status_counts" | awk '$2 == "\"expected\"" {print $1}')
          
          # Extract the count of the "unexpected" status value
          count_unexpected=$(echo "$status_counts" | awk '$2 == "\"unexpected\"" {print $1}')
          
          # if count_unexpected is not empty, exit with 1
          if [[ -n "$count_unexpected" ]]; then
            echo "Unexpected statuses found"
            echo "failed_test=true" >> ${GITHUB_OUTPUT}
          else
          # it means that all test passed, the failure is not related to the test
            echo "No unexpected statuses found"
            echo "failed_test=false" >> ${GITHUB_OUTPUT}
          fi
        
          # Print the counts
          echo "Number of expected statuses: $count_expected"
          echo "Number of unexpected statuses: $count_unexpected"
          
          # count_expected to GIT_OUTPUT
          echo "count_expected=$count_expected" >> ${GITHUB_OUTPUT}
          echo "count_unexpected=$count_unexpected" >> ${GITHUB_OUTPUT}
      -
        name: Prepare Links
        if: ${{ steps.analyze-report.outputs.failed_test == 'true' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ARTIFACT_NAME: test-report
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"
          
          check_suite_id=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/runs/${PREVIOUS_JOB_ID} \
            | jq -r '.check_suite_id')
          
          echo "check_suite_id: ${check_suite_id}"
          
          echo "ARTIFACT_NAME: ${ARTIFACT_NAME}"
          artifact_id=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/artifacts \
            | jq -r ".artifacts[] | select(.name == \"${ARTIFACT_NAME}\" and .expired == false) | select(.workflow_run.id == ${PREVIOUS_JOB_ID}) | .id")

          echo "artifact_id: ${artifact_id}"
          
          
          if [[ -n "${check_suite_id}" && -n "${artifact_id}" ]]; then
            ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/suites/${check_suite_id}/artifacts/${artifact_id}"
            echo "ARTIFACT_URL: ${ARTIFACT_URL}"
            echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"
          else
            echo "ARTIFACT_URL=not-available" >> "$GITHUB_ENV"
          fi
          
          PR_NUMBER=$(jq -r '.pull_requests[0].number' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Pull request Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
          
          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")
          
          echo "Head SHA: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"
      -
        name: Find Comment
        if: ${{ steps.analyze-report.outputs.failed_test == 'true' }}
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: tests_result_table
      -
        name: Create or update comment
        if: ${{ steps.analyze-report.outputs.failed_test == 'true' }}
        uses: peter-evans/create-or-update-comment@v3
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ env.PREVIOUS_JOB_ID }}"
          ARTIFACT_URL: ${{ env.ARTIFACT_URL }}
          HEAD_SHA: "${{ env.HEAD_SHA }}"
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          edit-mode: replace
          body: |-
            ![badge]
            <!---
            tests_result_table
            -->
            
            | Name          | Link                    |
            | --------      | ----------------------- |
            | Last Commit   | ${{ env.HEAD_SHA }}     |
            | Logs          | ${{ env.JOB_PATH }}     |
            | Download      | ${{ env.ARTIFACT_URL }} |
            
            [badge]: https://img.shields.io/badge/Test_Results-${{ steps.analyze-report.outputs.count_expected }}_Passed%20%7C%20${{ steps.analyze-report.outputs.count_unexpected }}%20Failed-red?style=for-the-badge&labelColor=0d1117&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIj8+CjxzdmcgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOmNjPSJodHRwOi8vd2ViLnJlc291cmNlLm9yZy9jYy8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgaWQ9InN2ZzIiIHZpZXdCb3g9IjAgMCA4NC44NTMgODQuODUzIiB2ZXJzaW9uPSIxLjAiPgogIDxnIGlkPSJsYXllcjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNTMuMjkgLTEzMi43OSkiPgogICAgPGcgaWQ9ImcyNzYyIiB0cmFuc2Zvcm09Im1hdHJpeCguNzA3MTEgLS43MDcxMSAuNzA3MTEgLjcwNzExIC02Ni41NzUgMTg5LjcxKSIgZmlsbD0icmVkIj4KICAgICAgPHJlY3QgaWQ9InJlY3QxODcyIiB5PSIxNjUuMjIiIHdpZHRoPSIxMDAiIHg9IjE0NS43MSIgaGVpZ2h0PSIyMCIvPgogICAgICA8cmVjdCBpZD0icmVjdDE4NzQiIHRyYW5zZm9ybT0icm90YXRlKDkwKSIgaGVpZ2h0PSIyMCIgd2lkdGg9IjEwMCIgeT0iLTIwNS43MSIgeD0iMTI1LjIyIi8+CiAgICA8L2c+CiAgPC9nPgogIDxtZXRhZGF0YT4KICAgIDxyZGY6UkRGPgogICAgICA8Y2M6V29yaz4KICAgICAgICA8ZGM6Zm9ybWF0PmltYWdlL3N2Zyt4bWw8L2RjOmZvcm1hdD4KICAgICAgICA8ZGM6dHlwZSByZGY6cmVzb3VyY2U9Imh0dHA6Ly9wdXJsLm9yZy9kYy9kY21pdHlwZS9TdGlsbEltYWdlIi8+CiAgICAgICAgPGNjOmxpY2Vuc2UgcmRmOnJlc291cmNlPSJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9wdWJsaWNkb21haW4vIi8+CiAgICAgICAgPGRjOnB1Ymxpc2hlcj4KICAgICAgICAgIDxjYzpBZ2VudCByZGY6YWJvdXQ9Imh0dHA6Ly9vcGVuY2xpcGFydC5vcmcvIj4KICAgICAgICAgICAgPGRjOnRpdGxlPk9wZW5jbGlwYXJ0PC9kYzp0aXRsZT4KICAgICAgICAgIDwvY2M6QWdlbnQ+CiAgICAgICAgPC9kYzpwdWJsaXNoZXI+CiAgICAgICAgPGRjOnRpdGxlPlggaWNvbjwvZGM6dGl0bGU+CiAgICAgICAgPGRjOmRhdGU+MjAwOC0wNC0wNFQwMzoyODo1MjwvZGM6ZGF0ZT4KICAgICAgICA8ZGM6ZGVzY3JpcHRpb24+R2FtZSBEZXNpZ24gZm9yIHB5d2VlayM2PC9kYzpkZXNjcmlwdGlvbj4KICAgICAgICA8ZGM6c291cmNlPmh0dHA6Ly9vcGVuY2xpcGFydC5vcmcvZGV0YWlsLzE2MTU1L3gtaWNvbi1ieS1taWxrZXItMTYxNTU8L2RjOnNvdXJjZT4KICAgICAgICA8ZGM6Y3JlYXRvcj4KICAgICAgICAgIDxjYzpBZ2VudD4KICAgICAgICAgICAgPGRjOnRpdGxlPm1pbGtlcjwvZGM6dGl0bGU+CiAgICAgICAgICA8L2NjOkFnZW50PgogICAgICAgIDwvZGM6Y3JlYXRvcj4KICAgICAgICA8ZGM6c3ViamVjdD4KICAgICAgICAgIDxyZGY6QmFnPgogICAgICAgICAgICA8cmRmOmxpPmNsaXAgYXJ0PC9yZGY6bGk+CiAgICAgICAgICAgIDxyZGY6bGk+Y2xpcGFydDwvcmRmOmxpPgogICAgICAgICAgICA8cmRmOmxpPmdhbWU8L3JkZjpsaT4KICAgICAgICAgICAgPHJkZjpsaT5pY29uPC9yZGY6bGk+CiAgICAgICAgICAgIDxyZGY6bGk+aW1hZ2U8L3JkZjpsaT4KICAgICAgICAgICAgPHJkZjpsaT5tZWRpYTwvcmRmOmxpPgogICAgICAgICAgICA8cmRmOmxpPnBuZzwvcmRmOmxpPgogICAgICAgICAgICA8cmRmOmxpPnB1YmxpYyBkb21haW48L3JkZjpsaT4KICAgICAgICAgICAgPHJkZjpsaT5zdmc8L3JkZjpsaT4KICAgICAgICAgIDwvcmRmOkJhZz4KICAgICAgICA8L2RjOnN1YmplY3Q+CiAgICAgIDwvY2M6V29yaz4KICAgICAgPGNjOkxpY2Vuc2UgcmRmOmFib3V0PSJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9wdWJsaWNkb21haW4vIj4KICAgICAgICA8Y2M6cGVybWl0cyByZGY6cmVzb3VyY2U9Imh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zI1JlcHJvZHVjdGlvbiIvPgogICAgICAgIDxjYzpwZXJtaXRzIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjRGlzdHJpYnV0aW9uIi8+CiAgICAgICAgPGNjOnBlcm1pdHMgcmRmOnJlc291cmNlPSJodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9ucyNEZXJpdmF0aXZlV29ya3MiLz4KICAgICAgPC9jYzpMaWNlbnNlPgogICAgPC9yZGY6UkRGPgogIDwvbWV0YWRhdGE+Cjwvc3ZnPgo=
          reactions: eyes
